---
author: Dustin Dortch
name: Get Current Version
description: Get the current version from the latest git tag

inputs:
  major-label:
    default: 'major'
    description: 'The label for the major version'
    required: false
  minor-label:
    default: 'minor'
    description: 'The label for the minor version'
    required: false
  patch-label:
    default: 'patch'
    description: 'The label for the patch version'
    required: false
  prerelease-label:
    default: 'pre-release'
    description: 'The label for the prerelease version'
    required: false
  no-release-label:
    default: 'no-release'
    description: 'The label for the no-release version'
    required: false

runs:
  using: composite
  steps:
    - name: Reject without labels
      id: reject_wo_labels
      shell: bash
      run: |
        EXIT_CODE=1
        for label in ${{ github.event.pull_request.labels.*.name }}; do
          case $label in 
            ${{ inputs.major-label }} | ${{ inputs.minor-label }} | ${{ inputs.patch-label }} | ${{ inputs.prerelease-label }} | ${{ inputs.no-release-label }})
              EXIT_CODE=0
              break
              ;;
          esac
        done

        if [ $EXIT_CODE -ne 0 ]; then
          echo "A major, minor, patch, pre-release, or no-release pull request label is required to merge to main."
        fi
        exit $EXIT_CODE
...