---
author: Dustin Dortch
name: Terraform Install
description: Installs Terraform

inputs:
  terraform_version:
    default: 'latest'
    description: 'The version of Terraform to install'
    required: false

runs:
  using: composite
  steps:
    - name: Tfenv Install
      id: tfenv_install
      shell: bash
      run: |
        git clone --depth=1 https://github.com/tfutils/tfenv.git ~/.tfenv
        sudo ln -sf ~/.tfenv/bin/* /usr/local/bin

    - name: Tfenv Version
      id: tfenv_version
      shell: bash
      run: |
        TFENV_VERSION=$(tfenv --version | awk 'BEGIN { FS = " " } ; { print $2}')
        echo "TFENV_VERSION: ${TFENV_VERSION}" >> $GITHUB_ENV

    - name: Terraform Install
      id: terraform_install
      shell: bash
      run: |
        tfenv install ${{ inputs.terraform_version }}

    - name: Terraform Version
      id: terraform_version
      shell: bash
      run: |
        TERRAFORM_VERSION=$(tfenv version-name)
        echo "TERRAFORM_VERSION: ${TERRAFORM_VERSION}" >> $GITHUB_ENV

...