---
name: Merge to main

on:
  pull_request:
    types:
      - closed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  tag_and_cherry_pick:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    if: github.event.repository.name != 'template-terraform' && github.event.merged == true
    steps:
      - name: Reject without labels
        id: reject_wo_labels
        uses: dustindortch/template-terraform/.github/actions/check_labels@main

      - uses: actions/checkout@v4

      - name: Get current version
        id: get_current_version
        uses: dustindortch/template-terraform/.github/actions/get_current_version@main
...
