---
name: Pull Request Review

on:
  pull_request_review:
    types:
      - submitted
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  terraform_apply:
    runs-on: ubuntu-latest
    # if: github.event.repository.name != 'template-terraform' && github.event.review.state == 'approved'
    if: github.event.review.state == 'approved'
    steps:
      - uses: actions/checkout@v4

      - name: Get pull request number
        id: pr_number
        shell: bash
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_OUTPUT

      - name: Download Artifact
        uses: actions/download-artifact@v4

      - name: Terraform Install
        id: terraform_install
        uses: dustindortch/template-terraform/.github/actions/terraform_install@main

      - name: Terraform Init
        id: terraform_init
        shell: bash
        run: |
          terraform init

      - name: Terraform Apply
        id: terraform_apply
        uses: dustindortch/template-terraform/.github/actions/terraform_apply@main
        with:
          github_token: ${{ github.token }}
          plan-file: 'tfplan'
          pr-id: ${{ steps.pr_number.outputs.PR_NUMBER }}

...
