---
name: Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  terraform_plan:
    runs-on: ubuntu-latest
    # if: github.event.repository.name != 'terraform-rootmodule-template' && github.event.review.state != 'approved'
    steps:
      - uses: actions/checkout@v4

      - name: Get pull request number
        id: pr_number
        shell: bash
        run: |
          PR_NUMBER=$(echo $GITHUB_REF | awk 'BEGIN { FS = "/" } ; { print $3 }')
          echo "PR_NUMBER: ${PR_NUMBER}"
          echo "PR_NUMBER=${PR_NUMBER}" >> $GITHUB_OUTPUT

      - name: Terraform Install
        id: terraform_install
        uses: dustindortch/terraform-rootmodule-template/.github/actions/terraform_install@main

      - name: Terraform Version
        id: terraform_version
        shell: bash
        run: |
          echo $TERRAFORM_VERSION
...
