---
name: Release

on:
  # pull_request:
  #   types:
  #     - closed
  workflow_dispatch:

permissions:
  contents: read
  id-token: write
  issues: write
  pull-requests: write

jobs:
  return-version:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
    env:
      GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # if: github.event.repository.name != 'template-terraform'
    # if: github.event.repository.name != 'template-terraform' && github.event.merged == true
    steps:
      - uses: actions/checkout@v4

      - name: Get next version
        id: next-version
        uses: dustindortch/gha-generate-semver@v1

      - name: Tag release
        run: |
          git config user.email "$(git --no-pager log --format=format:'%an' -n 1)"
          git config user.email "$(git --no-pager log --format=format:'%ae' -n 1)"
          git tag -a ${{ steps.next-version.outputs.new-version }} -m "Release ${{ steps.next-version.outputs.new-version }}"
          git push --mirror

      - name: Verify outputs
        run: |
          echo "New version: ${{ steps.next-version.outputs.new-version }}"
          echo "Previous version: ${{ steps.next-version.outputs.previous-version }}"
...
